apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuretech
  labels:
    app: insuretech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insuretech
  template:
    metadata:
      labels:
        app: insuretech
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: insuretech
          image: ghcr.io/chashchinalex/scaletestapp:arm64
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
