apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insuretech
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: insuretech
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
