apiVersion: v1
kind: Service
metadata:
  name: insuretech
  labels:
    app: insuretech
spec:
  selector:
    app: insuretech
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
